import os, json
from datetime import datetime
from modules.core.asset_registry import all_records
from modules.core.alerts import get_recent
from modules.core.filestack import get_stack

def _now(): return datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
def _load(fn):
    try:
        p = os.path.join(get_stack(), fn)
        if os.path.exists(p):
            with open(p) as f: return json.load(f)
    except: pass
    return {}

def generate(output_path=None):
    recs = all_records()
    unauth = [r for r in recs if not r['authorized']]
    alerts = get_recent(50)
    critical = [a for a in alerts if a.get('severity')=='CRITICAL']
    high = [a for a in alerts if a.get('severity')=='HIGH']
    hosts = _load('hosts.json').get('hosts',[])
    portscan = _load('portscan.json').get('scans',[])
    cve = _load('cve_findings.json')
    mitre = _load('mitre_findings.json')
    lines = []
    lines.append(f"# WRAITH Network Intelligence Report")
    lines.append(f"**Generated:** {_now()}")
    lines.append(f"**Classification:** Operator Confidential")
    lines.append(f"**Tool:** WRAITH v4.6 — passive OT/BAS network intelligence")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"WRAITH passive observation identified **{len(recs)} devices** on the monitored subnet.")
    if unauth:
        lines.append(f"**{len(unauth)} devices are unauthorized** and require immediate review.")
    if critical:
        lines.append(f"**{len(critical)} CRITICAL alerts** are active.")
    lines.append("")
    return lines, recs, unauth, alerts, critical, high, portscan, cve, mitre

def _inventory_section(recs):
    lines = []
    lines.append("## Network Inventory")
    lines.append("")
    lines.append(f"| IP | Type | Auth | Vendor | Protocols | First Seen | Last Seen |")
    lines.append(f"|---|---|---|---|---|---|---|")
    for r in sorted(recs, key=lambda x: x['network']['ip']):
        ip = r['network']['ip']
        typ = r['type']
        auth = 'YES' if r['authorized'] else '**NO**'
        vendor = r['network']['vendor'] or 'unknown'
        protos = ','.join(r['protocols']) if r['protocols'] else 'none'
        first = r['temporal']['first_seen'][:10]
        last = r['temporal']['last_seen'][:10]
        lines.append(f"| {ip} | {typ} | {auth} | {vendor} | {protos} | {first} | {last} |")
    lines.append("")
    return lines

def _threat_section(recs, alerts, critical, high):
    lines = []
    lines.append("## Threat Findings")
    lines.append("")
    unauth = [r for r in recs if not r['authorized']]
    if unauth:
        lines.append(f"### Unauthorized Devices ({len(unauth)})")
        lines.append("")
        for r in unauth:
            ip = r['network']['ip']
            ports = r['network']['open_ports']
            flags = r['threat']['ioc_flags']
            lines.append(f"- **{ip}** — ports={ports} ioc={flags}")
        lines.append("")
    if critical or high:
        lines.append(f"### Active Alerts")
        lines.append("")
        for a in (critical + high)[:20]:
            ts = a.get('timestamp','')[:19]
            sev = a.get('severity','')
            src = a.get('source','')
            msg = a.get('message','')[:100]
            lines.append(f"- `[{sev}]` {ts} **{src}**: {msg}")
        lines.append("")
    return lines

def _recommendations(recs, cve):
    lines = []
    lines.append("## Recommendations")
    lines.append("")
    unauth = [r for r in recs if not r['authorized']]
    if unauth:
        lines.append(f"1. **Review {len(unauth)} unauthorized devices** — authorize known assets, investigate unknown")
    lines.append("2. **Obtain MAC addresses** — current registry has no vendor validation")
    lines.append("3. **Deploy on SPAN port** — current visibility limited to broadcast traffic only")
    lines.append("4. **Enable SNMP monitoring** — extend protocol visibility to all devices")
    findings = cve.get('findings',{})
    if findings:
        lines.append(f"5. **Patch CVE exposures** — {cve.get('total',0)} CVEs identified")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by WRAITH — passive OT/BAS network intelligence*")
    lines.append("*sig.int.ghost — the wire does not lie*")
    return lines

def run_report():
    import time
    ts = time.strftime('%Y%m%d_%H%M%S')
    out = os.path.expanduser(f'~/.wraith/reports/wraith_report_{ts}.md')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    lines, recs, unauth, alerts, critical, high, portscan, cve, mitre = generate()
    lines += _inventory_section(recs)
    lines += _threat_section(recs, alerts, critical, high)
    lines += _recommendations(recs, cve)
    with open(out,'w') as f: f.write('\n'.join(lines))
    print(f"  [REPORT] written: {out}")
    print(f"  [REPORT] {len(recs)} devices, {len(unauth)} unauthorized")
    return out
